version: '3.9'

services:
  mariadb:
    image: mariadb:10.9.3
    ports:
      - 33900:3306
    volumes:
      - ~/apps/blenderi:/var/lib/mysql
    environment:
      - MYSQL_HOST
      - MYSQL_PORT
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
