version: '3.9'

services:
  mariadb:
    image: mariadb:10.9.3
    ports:
      - '${MYSQL_PORT}:3306'
    volumes:
      - blenderi-volume:/var/lib/mysql
    env_file:
      - .env
    environment:
      - MYSQL_HOST
      - MYSQL_PORT
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    command: mysqld --sql_mode="IGNORE_SPACE,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
  redis:
    image: redis:7.0.5-alpine3.16
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis-volume:/data
volumes:
  blenderi-volume:
    name: ${DB_VOLUME_NAME}
  redis-volume:
    name: ${REDIS_VOLUME_NAME}
