# fly.toml app configuration file generated for tayttopaikka-backend on 2023-08-13T12:42:48+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

kill_timeout = 42

app = "tayttopaikka-backend"
primary_region = "ams"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[http_service.checks]]
  grace_period = "42s"
  interval = "30s"
  method = "GET"
  timeout = "10s"
  path = "/api/utils/heartbeat"

[deploy]
  strategy = "canary"
